--
-- Table structure for table `#__jsptickets_attachements`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_attachements` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `ticket_id` int(11) NOT NULL COMMENT 'id of the ticket for which attachment is uploaded',
  `attachement_name` varchar(255) NOT NULL COMMENT 'name of the attachment. format: ticketid_filename_timestamp.ext',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'timestamp on which attachement is added',
  `created_by` int(11) NOT NULL COMMENT 'user id of user who has added attachement',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_audit`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key of the table, auto incremented',
  `ticket_id` int(11) NOT NULL COMMENT 'id of the ticket for which narration is added',
  `narration` mediumtext NOT NULL COMMENT 'narration for the ticket',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time stamp on which narration is added',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_categories`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `parent_id` int(11) NOT NULL COMMENT 'id of parent category',
  `lft` int(11) NOT NULL DEFAULT '0',
  `rgt` int(11) NOT NULL DEFAULT '0',
  `level` int(10) NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL COMMENT 'name of the category',
  `description` mediumtext NOT NULL COMMENT 'decription of category',
  `image` varchar(255) DEFAULT NULL COMMENT 'image name of the relative category',
  `publish` tinyint(3) NOT NULL COMMENT 'status-1 for publish and 0 for unpublish',
  `assigned_to` text NOT NULL COMMENT 'json format text, this can be assigned to multiple users',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_comments`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `ticket_id` int(11) NOT NULL COMMENT 'id of the ticket for which comment is added',
  `comments` mediumtext NOT NULL COMMENT 'comments for the ticket',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'timestamp on which comment is added',
  `created_by` int(11) NOT NULL COMMENT 'user id of user who has submitted comment',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_configuration`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_configuration` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto incremented',
  `file_upload` tinyint(3) NOT NULL COMMENT 'status-1 to allow add attachment and 0 to deny add attachment',
  `file_types` text NOT NULL COMMENT 'extensions (file types) that can be added by users',
  `load_jquery` tinyint(3) NOT NULL COMMENT '"status-2" for "Auto" load jQuery if not loaded, "status-1" for "Yes" definitely load jQuery and "status-0" for not loading the jQuery',
  `access_control` tinyint(3) NOT NULL COMMENT 'status-1 for guest/public submission of ticket and status-0 for allowing only registered users to submit ticket',
  `filter_option_access` varchar(255) NOT NULL,
  `select_category` tinyint(3) NOT NULL COMMENT 'Option to set "Select Category" field mandatory (status-1) or not (status-0) at the time of ticket submission',
  `email_notification` tinyint(3) NOT NULL COMMENT 'Option to set "Send Email Notifications" (status-1 to send) or (status-0 not to send) e-mails at the time of ticket submission/updation',
  `admin_email_id` text NOT NULL,
  `gen_fb_tickets` tinyint(3) NOT NULL COMMENT 'status 1 to allow',
  `fb_app_id` varchar(255) NOT NULL,
  `fb_app_secret` varchar(255) NOT NULL,
  `fb_page_url` text NOT NULL,
  `socialticket_gen_timeinterval` int(30) NOT NULL COMMENT 'time interval in which the plugin will be searching for the feeds from social media',
  `fb_filter_words` text NOT NULL,
  `fb_send_mail` tinyint(3) NOT NULL,
  `social_feed_triggered` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'stores timestamp of last when the social feeds where triggered.',
  `last_fbpost_time` varchar(255) NOT NULL,
  `fb_ticket_title` varchar(255) NOT NULL COMMENT 'the title for the tickets generated by social media',
  `fb_ticket_subject` varchar(255) NOT NULL COMMENT 'the subject for the tickets generated by social media',
  `gen_twitter_tickets` tinyint(3) NOT NULL,
  `custom_twitter_consumerkey` varchar(255) NOT NULL,
  `custom_twitter_consumersecret` varchar(255) NOT NULL,
  `custom_twitter_accesstoken` varchar(255) NOT NULL,
  `custom_twitter_accesstoken_secret` varchar(255) NOT NULL,
  `twitter_screenname` text NOT NULL,
  `twitter_filter_words` text NOT NULL,
  `twitter_send_mail` tinyint(3) NOT NULL,
  `last_tweet_id` varchar(255) NOT NULL,
  `twitter_ticket_title` varchar(255) NOT NULL,
  `twitter_ticket_subject` varchar(255) NOT NULL,
  `category_extension` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `new_mail_subject` varchar(255) NOT NULL COMMENT 'stores mail subject for the user mail notification at creation of new ticket',
  `new_mail_body` text NOT NULL COMMENT 'stores mail body for the user mail notification at creation of new ticket',
  `comment_mail_subject` varchar(255) NOT NULL COMMENT 'stores mail subject for the user mail notification at creation of new comment',
  `comment_mail_body` text NOT NULL COMMENT 'stores mail body for the user mail notification at creation of new comment',
  `assignee_changed_mail_subject` varchar(255) NOT NULL COMMENT 'stores mail subject for the user mail notification on assignee change',
  `assignee_changed_mail_body` text NOT NULL COMMENT 'stores mail body for the user mail notification on assignee change',
  `ticket_saved_msg` varchar(255) NOT NULL,
  `ticket_removed_msg` varchar(255) NOT NULL,
  `ticket_followup_msg` varchar(255) NOT NULL,
  `ticket_removefollow_msg` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 ;

--
-- Dumping data for table `#__jsptickets_configuration`
--

INSERT IGNORE INTO `#__jsptickets_configuration` (`id`, `file_upload`, `file_types`, `load_jquery`, `access_control`, `filter_option_access`, `select_category`, `email_notification`, `admin_email_id`, `gen_fb_tickets`, `fb_app_id`, `fb_app_secret`, `fb_page_url`, `socialticket_gen_timeinterval`, `fb_filter_words`, `fb_send_mail`, `social_feed_triggered`, `last_fbpost_time`, `fb_ticket_title`, `fb_ticket_subject`, `gen_twitter_tickets`, `custom_twitter_consumerkey`, `custom_twitter_consumersecret`, `custom_twitter_accesstoken`, `custom_twitter_accesstoken_secret`, `twitter_screenname`, `twitter_filter_words`, `twitter_send_mail`, `last_tweet_id`, `twitter_ticket_title`, `twitter_ticket_subject`, `category_extension`, `status`, `new_mail_subject`, `new_mail_body`, `comment_mail_subject`, `comment_mail_body`, `assignee_changed_mail_subject`, `assignee_changed_mail_body`, `ticket_saved_msg`, `ticket_removed_msg`, `ticket_followup_msg`, `ticket_removefollow_msg`) VALUES
(1, 1, 'jpg,jpeg,png,bmp,zip,txt,doc,rtf', 2, 0, '["1"]', 1, 1, 'admin1@gmail.com,admin2@gmail.com', 0, '', '', 'https://www.facebook.com/Microsoft', 10080, 'bug,error,issue', 1, '', '', 'Facebook Ticket Title', 'Facebook Ticket Subject', 0, '', '', '', '', 'Apple', 'bug,error,issue,fix', 1, '', 'Twitter Ticket Title', 'Twitter Ticket Subject', '["com_jsptickets"]', '["2","3","5"]', 'Ticket created successfully at', 'We have received your query.', 'New Comment received on', "New Comment's details given below:", 'A Ticket is Assigned to you', "Ticket's details given below:", 'Ticket Saved Successfully', 'Selected Item[s] removed Successfully', 'Ticket[s] marked for Follow Up.', 'Ticket[s] unmarked from Follow Up.');

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_feedbacks`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_feedbacks` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `ticket_id` int(11) NOT NULL COMMENT 'id of the ticket for which feedback is submitted',
  `feedbacks` mediumtext NOT NULL COMMENT 'feedbacks submitted by users',
  `rating` int(5) NOT NULL COMMENT 'rating out of 5 submitted by users',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'timestamp on which feedback is submitted',
  `created_by` int(11) NOT NULL COMMENT 'user id of user who has submitted feedback',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_priorities`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_priorities` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `name` varchar(255) NOT NULL COMMENT 'name of the priority',
  `description` mediumtext NOT NULL COMMENT 'description for priority',
  `publish` tinyint(3) NOT NULL COMMENT 'status-1 for publish and 0 for unpublish',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 ;

--
-- Dumping data for table `#__jsptickets_priorities`
--

INSERT IGNORE INTO `#__jsptickets_priorities` (`id`, `name`, `description`, `publish`) VALUES
(1, 'Low', 'low', 1),
(2, 'Medium', 'medium', 1),
(3, 'High', 'high', 1);

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_status`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto imcremented',
  `name` varchar(255) NOT NULL COMMENT 'name of the status',
  `description` mediumtext NOT NULL COMMENT 'description for status',
  `publish` tinyint(3) NOT NULL COMMENT 'status-1 for publish and 0 for unpublish',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 ;

--
-- Dumping data for table `#__jsptickets_status`
--

INSERT IGNORE INTO `#__jsptickets_status` (`id`, `name`, `description`, `publish`) VALUES
(1, 'New', 'new', 1),
(2, 'Closed', 'ticket closed', 1),
(3, 'Open', 'ticket open', 1),
(4, 'On hold', 'ticket on hold', 1),
(5, 'Re-open', 're-open', 1);

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_ticket`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_ticket` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key of the table, auto incremented',
  `ticketcode` varchar(255) NOT NULL COMMENT 'Random string for Ticket Id',
  `title` varchar(255) NOT NULL COMMENT 'title of the ticket ',
  `subject` varchar(255) NOT NULL COMMENT 'subject of the ticket raised',
  `description` mediumtext NOT NULL COMMENT 'description of ticket',
  `category_extension` varchar(255) NOT NULL COMMENT 'Keeps record of category''s extension chosen',
  `category_id` text NOT NULL COMMENT 'json format of foreign keys on this table WRT primary key of #__jspticket_categories table',
  `priority_id` int(11) NOT NULL COMMENT 'foreign key on this table WRT primary key of #__jspticket_priorities table',
  `status_id` int(11) NOT NULL COMMENT 'foreign key on this table WRT primary key of #__jspticket_status table',
  `attachment_id` text NOT NULL COMMENT 'json format text, contaning ids of attachements for this ticket',
  `feedback_id` text NOT NULL COMMENT 'foreign key on this table WRT primary key of #__jspticket_feedbacks table',
  `comment_id` text NOT NULL COMMENT 'json format text, contaning ids of comments for this ticket',
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'timestamp on which ticket is added',
  `created_by` int(11) NOT NULL COMMENT 'user_id of the user who has created ticket initially',
  `created_for` int(11) NOT NULL,
  `modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'timestamp of modification in tickets',
  `closed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'timestamp of closing of tickets',
  `assigned_by` int(11) NOT NULL COMMENT 'user_id of the user who has assigned this ticket to another user',
  `assigned_to` int(11) NOT NULL COMMENT 'user_id of the user to whom ticket is assigned',
  `closed_by` int(11) NOT NULL COMMENT 'user_id of the user who has closed the ticket',
  `checked_out` int(11) NOT NULL COMMENT 'user_id of the user who has checked out ticket',
  `checked_out_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'time stamp on which user has checked out ticket',
  `email_comment` enum('0','1') NOT NULL DEFAULT '0' COMMENT 'to send email on new comment or not',
  `follow_up` enum('0','1') NOT NULL DEFAULT '0' COMMENT 'ticket follow_up flag',
  `guestname` varchar(255) NOT NULL,
  `guestemail` varchar(255) NOT NULL,
  `fb_post_id` varchar(255) NOT NULL,
  `tweet_id` varchar(255) NOT NULL,
  `twitter_username` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `#__jsptickets_temp_categories`
--

CREATE TABLE IF NOT EXISTS `#__jsptickets_temp_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asset_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.',
  `parent_id` int(10) unsigned NOT NULL DEFAULT '0',
  `lft` int(11) NOT NULL DEFAULT '0',
  `rgt` int(11) NOT NULL DEFAULT '0',
  `level` int(10) unsigned NOT NULL DEFAULT '0',
  `path` varchar(255) NOT NULL DEFAULT '',
  `extension` varchar(50) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `note` varchar(255) NOT NULL DEFAULT '',
  `description` mediumtext NOT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `checked_out` int(11) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `access` int(10) unsigned NOT NULL DEFAULT '0',
  `params` text NOT NULL,
  `metadesc` varchar(1024) NOT NULL COMMENT 'The meta description for the page.',
  `metakey` varchar(1024) NOT NULL COMMENT 'The meta keywords for the page.',
  `metadata` varchar(2048) NOT NULL COMMENT 'JSON encoded metadata properties.',
  `created_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `created_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `modified_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `language` char(7) NOT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `cat_idx` (`extension`,`published`,`access`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_path` (`path`),
  KEY `idx_left_right` (`lft`,`rgt`),
  KEY `idx_alias` (`alias`),
  KEY `idx_language` (`language`)
) ENGINE=MyISAM AUTO_INCREMENT=1 ;

-- --------------------------------------------------------